version: "3.7"
services:
  motorhead:
    image: ghcr.io/getmetal/motorhead:v2.0.4
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    environment:
      - MOTORHEAD_LONG_TERM_MEMORY=true
      - PORT=8080
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
